-- Seed do instrumento proprietário V2. Rode após as migrations iniciais.

insert into public.questionnaires (code, version, title, status, methodology_status, source_notes) values
('PSICO_V2', '4.0-v2-supabase-ready', 'Triagem e Monitoramento Psicossocial V2', 'active', 'Instrumento proprietário em validação técnica', 'Inspirado em domínios reconhecidos: demandas, controle, apoio social, liderança, justiça, segurança psicológica, conflito trabalho-vida, exaustão e eventos sentinela. Não reproduz instrumento validado específico.')
on conflict (code) do update set version = excluded.version, title = excluded.title, status = excluded.status, methodology_status = excluded.methodology_status, source_notes = excluded.source_notes;

with q as (select id from public.questionnaires where code = 'PSICO_V2')
insert into public.domains (questionnaire_id, code, name, description, sort_order) values
((select id from q), 'DEM', 'Demandas, ritmo e carga de trabalho', 'Volume, pressão temporal, metas, ritmo e exigência mental percebida.', 1),
((select id from q), 'CTL', 'Controle, autonomia e participação na tarefa', 'Margem de decisão, influência sobre o próprio trabalho e possibilidade de ajuste do ritmo.', 2),
((select id from q), 'ROL', 'Clareza de papel e qualidade da informação', 'Clareza de expectativas, responsabilidades, prioridades e informações para executar o trabalho.', 3),
((select id from q), 'LID', 'Liderança, justiça e suporte da chefia', 'Disponibilidade, respeito, orientação, justiça e reconhecimento pela liderança imediata.', 4),
((select id from q), 'APS', 'Apoio social, cooperação e pertencimento', 'Ajuda entre colegas, cooperação, confiança e sentimento de pertencimento ao grupo.', 5),
((select id from q), 'REC', 'Reconhecimento, justiça e desenvolvimento', 'Reciprocidade, justiça organizacional, oportunidades e equilíbrio na distribuição de tarefas.', 6),
((select id from q), 'CON', 'Conflitos, respeito e relações abusivas', 'Tratamento de conflitos, comunicação agressiva, isolamento, desrespeito e impacto nas relações.', 7),
((select id from q), 'SEG', 'Segurança psicológica e medo de retaliação', 'Liberdade para falar de problemas, erros e riscos sem medo de punição ou julgamento.', 8),
((select id from q), 'MUD', 'Comunicação de mudanças e participação', 'Antecedência, coerência, participação e retorno sobre mudanças ou problemas comunicados.', 9),
((select id from q), 'CTF', 'Conflito trabalho-vida pessoal e recuperação', 'Interferência do trabalho na vida pessoal, desligamento mental, pausas e recuperação entre jornadas.', 10),
((select id from q), 'EXA', 'Exaustão e sinais de desgaste', 'Exaustão, queda de energia, sensação de limite, irritabilidade, ansiedade ou tensão associada ao trabalho.', 11),
((select id from q), 'PRE', 'Prevenção, canais e cultura de cuidado', 'Conhecimento de canais, resposta organizacional, comunicação preventiva e compromisso com cuidado.', 12),
((select id from q), 'CRI', 'Sinais críticos e eventos sentinela', 'Sinais que exigem análise técnica, acolhimento, apuração adequada e medidas preventivas proporcionais.', 13)
on conflict (questionnaire_id, code) do update set name = excluded.name, description = excluded.description, sort_order = excluded.sort_order;

with q as (select id from public.questionnaires where code = 'PSICO_V2'), d as (select id, code from public.domains where questionnaire_id = (select id from q))
insert into public.questions (questionnaire_id, domain_id, code, text, question_type, direction, is_critical, is_required, sort_order) values
((select id from q), (select id from d where code = 'DEM'), 'Q01', 'Tenho que trabalhar em ritmo muito intenso para dar conta das minhas tarefas.', 'likert_frequency', 'risk', false, true, 1),
((select id from q), (select id from d where code = 'DEM'), 'Q02', 'A quantidade de trabalho é maior do que consigo realizar com qualidade no tempo disponível.', 'likert_frequency', 'risk', false, true, 2),
((select id from q), (select id from d where code = 'DEM'), 'Q03', 'As metas, prazos ou cobranças do trabalho geram pressão excessiva.', 'likert_frequency', 'risk', false, true, 3),
((select id from q), (select id from d where code = 'DEM'), 'Q04', 'Meu trabalho exige atenção constante ou esforço mental intenso por longos períodos.', 'likert_frequency', 'risk', false, true, 4),
((select id from q), (select id from d where code = 'CTL'), 'Q05', 'Tenho autonomia suficiente para decidir como organizar minhas tarefas.', 'likert_frequency', 'protective', false, true, 5),
((select id from q), (select id from d where code = 'CTL'), 'Q06', 'Consigo influenciar decisões que afetam diretamente o meu trabalho.', 'likert_frequency', 'protective', false, true, 6),
((select id from q), (select id from d where code = 'CTL'), 'Q07', 'Tenho liberdade adequada para propor melhorias no modo como o trabalho é feito.', 'likert_frequency', 'protective', false, true, 7),
((select id from q), (select id from d where code = 'CTL'), 'Q08', 'Posso ajustar meu ritmo de trabalho quando percebo sinais de cansaço ou sobrecarga.', 'likert_frequency', 'protective', false, true, 8),
((select id from q), (select id from d where code = 'ROL'), 'Q09', 'Sei claramente o que se espera de mim no trabalho.', 'likert_frequency', 'protective', false, true, 9),
((select id from q), (select id from d where code = 'ROL'), 'Q10', 'Recebo as informações necessárias para realizar bem minhas atividades.', 'likert_frequency', 'protective', false, true, 10),
((select id from q), (select id from d where code = 'ROL'), 'Q11', 'As responsabilidades entre pessoas e áreas são bem definidas.', 'likert_frequency', 'protective', false, true, 11),
((select id from q), (select id from d where code = 'ROL'), 'Q12', 'Quando há mudança de prioridade, recebo orientação clara sobre o que deve ser feito.', 'likert_frequency', 'protective', false, true, 12),
((select id from q), (select id from d where code = 'LID'), 'Q13', 'Minha liderança imediata está disponível para orientar quando preciso.', 'likert_frequency', 'protective', false, true, 13),
((select id from q), (select id from d where code = 'LID'), 'Q14', 'Minha liderança trata as pessoas com respeito e justiça.', 'likert_frequency', 'protective', false, true, 14),
((select id from q), (select id from d where code = 'LID'), 'Q15', 'Minha liderança ajuda a remover obstáculos que dificultam o trabalho.', 'likert_frequency', 'protective', false, true, 15),
((select id from q), (select id from d where code = 'LID'), 'Q16', 'Minha liderança reconhece esforços e contribuições da equipe.', 'likert_frequency', 'protective', false, true, 16),
((select id from q), (select id from d where code = 'APS'), 'Q17', 'Posso contar com colegas quando preciso de ajuda no trabalho.', 'likert_frequency', 'protective', false, true, 17),
((select id from q), (select id from d where code = 'APS'), 'Q18', 'Na minha equipe, as pessoas cooperam para resolver problemas.', 'likert_frequency', 'protective', false, true, 18),
((select id from q), (select id from d where code = 'APS'), 'Q19', 'Existe confiança suficiente para pedir ajuda sem medo de julgamento.', 'likert_frequency', 'protective', false, true, 19),
((select id from q), (select id from d where code = 'APS'), 'Q20', 'Sinto que faço parte de um grupo de trabalho respeitoso.', 'likert_frequency', 'protective', false, true, 20),
((select id from q), (select id from d where code = 'REC'), 'Q21', 'O esforço realizado no meu trabalho é reconhecido de forma adequada.', 'likert_frequency', 'protective', false, true, 21),
((select id from q), (select id from d where code = 'REC'), 'Q22', 'As regras, cobranças e decisões são aplicadas de forma justa.', 'likert_frequency', 'protective', false, true, 22),
((select id from q), (select id from d where code = 'REC'), 'Q23', 'Tenho oportunidades compatíveis de desenvolvimento e aprendizado.', 'likert_frequency', 'protective', false, true, 23),
((select id from q), (select id from d where code = 'REC'), 'Q24', 'A distribuição de tarefas é percebida como equilibrada na minha área.', 'likert_frequency', 'protective', false, true, 24),
((select id from q), (select id from d where code = 'CON'), 'Q25', 'Conflitos no trabalho costumam ficar sem tratamento adequado.', 'likert_frequency', 'risk', false, true, 25),
((select id from q), (select id from d where code = 'CON'), 'Q26', 'Presencio ou vivencio comunicação agressiva, humilhações ou ironias no trabalho.', 'likert_frequency', 'risk', false, true, 26),
((select id from q), (select id from d where code = 'CON'), 'Q27', 'Há competição, isolamento ou desrespeito que prejudica a convivência.', 'likert_frequency', 'risk', false, true, 27),
((select id from q), (select id from d where code = 'CON'), 'Q28', 'Problemas de relacionamento no trabalho afetam meu bem-estar ou desempenho.', 'likert_frequency', 'risk', false, true, 28),
((select id from q), (select id from d where code = 'SEG'), 'Q29', 'Evito falar sobre problemas do trabalho por medo de consequências negativas.', 'likert_frequency', 'risk', false, true, 29),
((select id from q), (select id from d where code = 'SEG'), 'Q30', 'Tenho receio de ser punido(a), prejudicado(a) ou malvisto(a) ao apontar riscos ou erros.', 'likert_frequency', 'risk', false, true, 30),
((select id from q), (select id from d where code = 'SEG'), 'Q31', 'Na minha área, erros são usados para culpabilizar pessoas em vez de melhorar processos.', 'likert_frequency', 'risk', false, true, 31),
((select id from q), (select id from d where code = 'SEG'), 'Q32', 'Sinto que opiniões divergentes não são bem recebidas no ambiente de trabalho.', 'likert_frequency', 'risk', false, true, 32),
((select id from q), (select id from d where code = 'MUD'), 'Q33', 'Mudanças que afetam meu trabalho são comunicadas com antecedência suficiente.', 'likert_frequency', 'protective', false, true, 33),
((select id from q), (select id from d where code = 'MUD'), 'Q34', 'As pessoas impactadas por mudanças têm oportunidade de participar ou opinar.', 'likert_frequency', 'protective', false, true, 34),
((select id from q), (select id from d where code = 'MUD'), 'Q35', 'A comunicação da empresa é coerente entre o que é dito e o que é praticado.', 'likert_frequency', 'protective', false, true, 35),
((select id from q), (select id from d where code = 'MUD'), 'Q36', 'Recebo retorno sobre dúvidas, solicitações ou problemas que levo à liderança.', 'likert_frequency', 'protective', false, true, 36),
((select id from q), (select id from d where code = 'CTF'), 'Q37', 'O trabalho interfere negativamente na minha vida pessoal ou familiar.', 'likert_frequency', 'risk', false, true, 37),
((select id from q), (select id from d where code = 'CTF'), 'Q38', 'Tenho dificuldade de me desligar mentalmente do trabalho fora do expediente.', 'likert_frequency', 'risk', false, true, 38),
((select id from q), (select id from d where code = 'CTF'), 'Q39', 'Preciso abrir mão de descanso, alimentação ou pausas por causa das demandas do trabalho.', 'likert_frequency', 'risk', false, true, 39),
((select id from q), (select id from d where code = 'CTF'), 'Q40', 'Sinto que o tempo de recuperação entre jornadas é insuficiente.', 'likert_frequency', 'risk', false, true, 40),
((select id from q), (select id from d where code = 'EXA'), 'Q41', 'Ao final do trabalho, sinto exaustão física ou emocional intensa.', 'likert_frequency', 'risk', false, true, 41),
((select id from q), (select id from d where code = 'EXA'), 'Q42', 'Tenho percebido queda de energia, motivação ou concentração por causa do trabalho.', 'likert_frequency', 'risk', false, true, 42),
((select id from q), (select id from d where code = 'EXA'), 'Q43', 'Sinto que estou no limite para continuar mantendo o mesmo ritmo de trabalho.', 'likert_frequency', 'risk', false, true, 43),
((select id from q), (select id from d where code = 'EXA'), 'Q44', 'O trabalho tem contribuído para irritabilidade, ansiedade ou tensão frequente.', 'likert_frequency', 'risk', false, true, 44),
((select id from q), (select id from d where code = 'PRE'), 'Q45', 'Conheço canais seguros para relatar situações de risco, conflito ou sofrimento no trabalho.', 'likert_frequency', 'protective', false, true, 45),
((select id from q), (select id from d where code = 'PRE'), 'Q46', 'A empresa demonstra agir quando problemas psicossociais são relatados.', 'likert_frequency', 'protective', false, true, 46),
((select id from q), (select id from d where code = 'PRE'), 'Q47', 'As medidas de prevenção e cuidado são comunicadas de forma clara aos trabalhadores.', 'likert_frequency', 'protective', false, true, 47),
((select id from q), (select id from d where code = 'PRE'), 'Q48', 'Percebo compromisso real da organização com saúde, segurança e respeito no trabalho.', 'likert_frequency', 'protective', false, true, 48),
((select id from q), (select id from d where code = 'CRI'), 'Q49', 'Vivenciei ou presenciei assédio moral, constrangimento repetido ou humilhação no trabalho.', 'likert_frequency', 'risk', true, true, 49),
((select id from q), (select id from d where code = 'CRI'), 'Q50', 'Vivenciei ou presenciei ameaça, intimidação ou violência psicológica no trabalho.', 'likert_frequency', 'risk', true, true, 50),
((select id from q), (select id from d where code = 'CRI'), 'Q51', 'Vivenciei ou presenciei conduta de conotação sexual indesejada no ambiente de trabalho.', 'likert_frequency', 'risk', true, true, 51),
((select id from q), (select id from d where code = 'CRI'), 'Q52', 'Senti medo de retaliação ao pensar em relatar situação grave no trabalho.', 'likert_frequency', 'risk', true, true, 52),
((select id from q), (select id from d where code = 'CRI'), 'Q53', 'Percebo que pessoas são isoladas, ridicularizadas ou perseguidas no ambiente de trabalho.', 'likert_frequency', 'risk', true, true, 53),
((select id from q), (select id from d where code = 'CRI'), 'Q54', 'Há situações no trabalho que considero graves e que não são tratadas pela organização.', 'likert_frequency', 'risk', true, true, 54),
((select id from q), (select id from d where code = 'CRI'), 'Q55', 'O nível de cansaço ou sofrimento relacionado ao trabalho tem me preocupado seriamente.', 'likert_frequency', 'risk', true, true, 55),
((select id from q), (select id from d where code = 'CRI'), 'Q56', 'Já pensei em pedir desligamento ou afastamento por causa das condições psicossociais do trabalho.', 'likert_frequency', 'risk', true, true, 56),
((select id from q), null, 'A1', 'Quais situações do trabalho mais contribuem para estresse, desgaste ou sofrimento?', 'open_text', 'neutral', false, false, 101),
((select id from q), null, 'A2', 'Que mudanças poderiam melhorar a organização do trabalho, a saúde e o bem-estar da equipe?', 'open_text', 'neutral', false, false, 102),
((select id from q), null, 'A3', 'Existe algum risco, conflito ou situação grave que a empresa deveria analisar com cuidado?', 'open_text', 'neutral', false, false, 103),
((select id from q), null, 'A4', 'Há alguma prática positiva que deveria ser mantida ou fortalecida?', 'open_text', 'neutral', false, false, 104)
on conflict (questionnaire_id, code) do update set domain_id = excluded.domain_id, text = excluded.text, question_type = excluded.question_type, direction = excluded.direction, is_critical = excluded.is_critical, is_required = excluded.is_required, sort_order = excluded.sort_order;
